- name: Init Terraform
  shell: |
    cd {{ playbook_dir }}/docker-nexus;
    terraform init    
  delegate_to: localhost
  register: init


- name: "Display output: Init Terraform"
  debug:
    msg: "{{ init.stdout }}"


- name: Create resources - Plan
  shell: |
    cd {{ playbook_dir }}/docker-nexus;
    terraform plan   
  delegate_to: localhost
  register: create_plan


- name: "Display output: Create resources - Plan"
  debug:
    msg: "{{ create_plan.stdout }}"


# - name: Create resources - apply
#   shell: |
#     cd {{ playbook_dir }}/docker-nexus;
#     terraform apply    
#   delegate_to: localhost
#   register: create


- name: Create resources - apply
  expect:
    command: cd {{ playbook_dir }}/docker-nexus; terraform apply
    responses:
      Enter a value: "yes"
  # you don't want to show passwords in your logs
  no_log: true
  delegate_to: localhost
  register: create


- name: "Display output: Create resources"
  debug:
    msg: "{{ create.stdout }}"
